//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoiQuaTet.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGCComboGiaTienEntities : DbContext
    {
        public SGCComboGiaTienEntities()
            : base("name=SGCComboGiaTienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AHFSData> AHFSDatas { get; set; }
        public virtual DbSet<AssociatedCombo> AssociatedComboes { get; set; }
        public virtual DbSet<Combo> Comboes { get; set; }
        public virtual DbSet<ComboGroup> ComboGroups { get; set; }
        public virtual DbSet<ComboProduct> ComboProducts { get; set; }
        public virtual DbSet<ComboStoreGroup> ComboStoreGroups { get; set; }
        public virtual DbSet<ComboType> ComboTypes { get; set; }
        public virtual DbSet<CostBasedChargeDetail> CostBasedChargeDetails { get; set; }
        public virtual DbSet<DeliveryChargeDetail> DeliveryChargeDetails { get; set; }
        public virtual DbSet<DeliveryChargePolicy> DeliveryChargePolicies { get; set; }
        public virtual DbSet<DeliveryRecord> DeliveryRecords { get; set; }
        public virtual DbSet<DeliveryTimeConfig> DeliveryTimeConfigs { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventComboType> EventComboTypes { get; set; }
        public virtual DbSet<FileAttachment> FileAttachments { get; set; }
        public virtual DbSet<FileAttachmentData> FileAttachmentDatas { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderAddress> OrderAddresses { get; set; }
        public virtual DbSet<OrderCombo> OrderComboes { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<OrderUpdateStatusHistory> OrderUpdateStatusHistories { get; set; }
        public virtual DbSet<SaleBanner> SaleBanners { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreGroup> StoreGroups { get; set; }
        public virtual DbSet<StoreGroupDetail> StoreGroupDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TextConfig> TextConfigs { get; set; }
    }
}
