//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoiQuaTet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public int CustomerAddressId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverEmail { get; set; }
        public int ReceiverAddressId { get; set; }
        public bool SendToCustomer { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal PaidPrice { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> DeliveryRecordId { get; set; }
        public string Note { get; set; }
        public decimal Charge { get; set; }
        public string StringId { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public int Distance { get; set; }
        public int EventId { get; set; }
        public int MinimumPaymentRequire { get; set; }
        public Nullable<int> OrderStoreId { get; set; }
    }
}
