//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoiQuaTet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCombo
    {
        public int OrderId { get; set; }
        public int ComboId { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }
        public string Note { get; set; }
        public int Id { get; set; }
    }
}
