//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoiQuaTet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleBanner
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public int Style { get; set; }
        public string Header { get; set; }
        public string HeaderColor { get; set; }
        public string Description { get; set; }
        public string DescriptionColor { get; set; }
        public int Animation { get; set; }
        public bool IsMobile { get; set; }
        public bool IsActive { get; set; }
        public string Url { get; set; }
        public int EventId { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
