//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoiQuaTet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AccountInfo { get; set; }
        public string ContactInfo { get; set; }
        public string Email { get; set; }
        public bool OnlinePayment { get; set; }
        public double Longtitude { get; set; }
        public double Latitude { get; set; }
        public string City { get; set; }
    }
}
